insert into users (username, password, name, salt) values ('detty0', 'ZgSQwUV', 'Devonna Etty', 66);
insert into users (username, password, name, salt) values ('xkinnier1', 'c3oQWN', 'Ximenes Kinnier', 63);
insert into users (username, password, name, salt) values ('zgaythwaite2', '7JHLubQM', 'Zane Gaythwaite', 83);
insert into users (username, password, name, salt) values ('pvedeneev3', 'viOFRskEkM4', 'Piper Vedeneev', 34);
insert into users (username, password, name, salt) values ('dverdey4', 'QNvG61', 'Debora Verdey', 45);
insert into users (username, password, name, salt) values ('hspottiswoode5', '3luB7DjE', 'Hector Spottiswoode', 46);
insert into users (username, password, name, salt) values ('rhathorn6', 'Jvkh8ffiYeT', 'Rosalyn Hathorn', 79);
insert into users (username, password, name, salt) values ('rbeane7', 'swu1vwtIFr', 'Reggis Beane', 22);
insert into users (username, password, name, salt) values ('rfontaine8', 'rYeP8VA', 'Randene Fontaine', 6);
insert into users (username, password, name, salt) values ('mconford9', 'uge2nDjox7', 'Michaella Conford', 55);
insert into users (username, password, name, salt) values ('tdrillingcourta', 'DWZWpBOy', 'Tadeas Drillingcourt', 83);
insert into users (username, password, name, salt) values ('aurridgeb', 'laPNNU6aLo', 'Abelard Urridge', 72);
insert into users (username, password, name, salt) values ('clukasc', 'F5XYjsLmj', 'Carlina Lukas', 22);
insert into users (username, password, name, salt) values ('ccarpmiled', 'foKu6J6vE', 'Crista Carpmile', 74);
insert into users (username, password, name, salt) values ('gemblowe', 'UXgr0vNAC', 'Ginevra Emblow', 26);
insert into users (username, password, name, salt) values ('abrizlandf', 'kHVe7sy', 'Angelle Brizland', 63);
insert into users (username, password, name, salt) values ('hsnufflebottomg', 'zzgvcW4w', 'Henka Snufflebottom', 35);
insert into users (username, password, name, salt) values ('ifarnorthh', 'lt6AxhIsx', 'Illa Farnorth', 4);
insert into users (username, password, name, salt) values ('mwreyi', 'wMpGS1vu', 'Marjory Wrey', 45);
insert into users (username, password, name, salt) values ('earndellj', 'W68vnFjQd12', 'Eldridge Arndell', 35);
insert into users (username, password, name, salt) values ('rrainsdenk', 'BCbgCcT', 'Rosalinde Rainsden', 70);
insert into users (username, password, name, salt) values ('hdrakardl', 'l59cNnc5xpf', 'Hort Drakard', 14);
insert into users (username, password, name, salt) values ('lbowdlerm', 'UQTxaGH', 'Lammond Bowdler', 45);
insert into users (username, password, name, salt) values ('jneaven', 'kCJbPMtNhHPz', 'Jordon Neave', 54);
insert into users (username, password, name, salt) values ('hjonkeo', 'ts5wxN7', 'Hadleigh Jonke', 99);
insert into users (username, password, name, salt) values ('cscarrep', 'pcRgeajknh', 'Constance Scarre', 53);
insert into users (username, password, name, salt) values ('rtorranceq', '8EclM1', 'Robbi Torrance', 54);
insert into users (username, password, name, salt) values ('bfessionsr', 'RShEd4lcO', 'Barbe Fessions', 30);
insert into users (username, password, name, salt) values ('ddolbeys', 'gzT0ZRuL3c', 'Dynah Dolbey', 12);
insert into users (username, password, name, salt) values ('ispatonit', 'uyWO7HUd', 'Ilaire Spatoni', 84);
insert into users (username, password, name, salt) values ('bjakobssenu', 'kLsh9oJYyPn2', 'Bartlett Jakobssen', 92);
insert into users (username, password, name, salt) values ('ifreev', 'Ll56jOlI5Y', 'Idell Free', 3);
insert into users (username, password, name, salt) values ('vmckeaveneyw', 'hXlzX68DYV', 'Veda McKeaveney', 13);
insert into users (username, password, name, salt) values ('tmicheaux', 'i1PTGdJBvOTl', 'Torrin Micheau', 45);
insert into users (username, password, name, salt) values ('dvorleyy', 'Bq36tv', 'Darnall Vorley', 9);
insert into users (username, password, name, salt) values ('ariponz', 'jEA67E', 'Alethea Ripon', 35);
insert into users (username, password, name, salt) values ('lreoch10', 'MOAqi7J5', 'Lazare Reoch', 28);
insert into users (username, password, name, salt) values ('cpeasegood11', '4rbw6h', 'Carce Peasegood', 99);
insert into users (username, password, name, salt) values ('twimpeney12', 'pNVjcHWnYM', 'Tammy Wimpeney', 14);
insert into users (username, password, name, salt) values ('ashufflebotham13', 'fsiFmPlTXS', 'Arlan Shufflebotham', 42);
insert into users (username, password, name, salt) values ('lcalwell14', 'Lin3UfKOQcFM', 'Laney Calwell', 60);
insert into users (username, password, name, salt) values ('kstandering15', 'Kj200jau0', 'Korey Standering', 19);
insert into users (username, password, name, salt) values ('ibladen16', '3amzlAE', 'Isaak Bladen', 51);
insert into users (username, password, name, salt) values ('rcoakley17', '8uLLVtu2PK', 'Rabbi Coakley', 26);
insert into users (username, password, name, salt) values ('ccains18', 'ncH1qWsVD', 'Charity Cains', 35);
insert into users (username, password, name, salt) values ('tpattillo19', '6j2jjSHp', 'Thane Pattillo', 28);
insert into users (username, password, name, salt) values ('acanedo1a', 'CNPODSNzlmWE', 'Ashby Canedo', 38);
insert into users (username, password, name, salt) values ('tgrishin1b', 'hWhBZNS', 'Talia Grishin', 99);
insert into users (username, password, name, salt) values ('ahynes1c', 'FcmNf8uog', 'Aurthur Hynes', 5);
insert into users (username, password, name, salt) values ('yyesenev1d', 'YMtlmNe8HDok', 'Yolande Yesenev', 40);
insert into users (username, password, name, salt) values ('ofanthom1e', 'N6cijW', 'Orsola Fanthom', 72);
insert into users (username, password, name, salt) values ('tanton1f', 'qAV77cVAGr5', 'Thorstein Anton', 51);
insert into users (username, password, name, salt) values ('zgourlie1g', 'TkIRHqmmYEV', 'Zebadiah Gourlie', 37);
insert into users (username, password, name, salt) values ('jfieller1h', 'iT8sFC', 'Jaymee Fieller', 76);
insert into users (username, password, name, salt) values ('spearch1i', 'ChQE5dtCUC', 'Samson Pearch', 60);
insert into users (username, password, name, salt) values ('jshildrick1j', '11ovVSd', 'Jacqui Shildrick', 62);
insert into users (username, password, name, salt) values ('sandryszczak1k', 'VIFWUlRdD', 'Skip Andryszczak', 7);
insert into users (username, password, name, salt) values ('gclapperton1l', 'B1GD5ZVyzdFv', 'Godwin Clapperton', 83);
insert into users (username, password, name, salt) values ('jchastaing1m', 'oR95wk4RyBdV', 'Josias Chastaing', 16);
insert into users (username, password, name, salt) values ('scoalburn1n', 'BudAD0KXH', 'Stormie Coalburn', 84);
insert into users (username, password, name, salt) values ('btomas1o', 'Sx33BGUE', 'Bart Tomas', 28);
insert into users (username, password, name, salt) values ('bvanezis1p', 'Q79DZJN', 'Bethena Vanezis', 10);
insert into users (username, password, name, salt) values ('pfrudd1q', 'gVyJFoMWS0X', 'Paola Frudd', 48);
insert into users (username, password, name, salt) values ('rlinford1r', 'A3zrnm', 'Renate Linford', 87);
insert into users (username, password, name, salt) values ('mdiperaus1s', 'HfXLp9F', 'Menard Diperaus', 96);
insert into users (username, password, name, salt) values ('vpember1t', 'qEjZUxF', 'Vail Pember', 20);
insert into users (username, password, name, salt) values ('vcripwell1u', '6jk9QeS9GLs', 'Victoir Cripwell', 3);
insert into users (username, password, name, salt) values ('ethomassin1v', 'SEvx1oOOUWTX', 'Emmet Thomassin', 51);
insert into users (username, password, name, salt) values ('dzorn1w', 'q4gKowE', 'Dorice Zorn', 85);
insert into users (username, password, name, salt) values ('bbreddy1x', 'BuAGkhz', 'Boyd Breddy', 94);
insert into users (username, password, name, salt) values ('acastri1y', 'JxcR8hNk3x', 'Alfredo Castri', 5);
insert into users (username, password, name, salt) values ('nwingfield1z', 'L5oApoiIR3', 'Nelson Wingfield', 33);
insert into users (username, password, name, salt) values ('aantowski20', 'n8to7Q', 'Abraham Antowski', 23);
insert into users (username, password, name, salt) values ('gmolfino21', '9eQZBJmmMMv5', 'Gunter Molfino', 42);
insert into users (username, password, name, salt) values ('pdaleman22', 'MDr4AWQOva', 'Pebrook Daleman', 76);
insert into users (username, password, name, salt) values ('alomond23', 'ELGv0G4Krt', 'Ali Lomond', 14);
insert into users (username, password, name, salt) values ('eblaze24', 'UpWa4oPS', 'Eddi Blaze', 72);
insert into users (username, password, name, salt) values ('kchasmor25', 'hY9E2vqvtwj', 'Kara Chasmor', 92);
insert into users (username, password, name, salt) values ('dattarge26', 'VKyggaWLO', 'Delcina Attarge', 49);
insert into users (username, password, name, salt) values ('wantognoni27', 'DSuyKsU', 'Wylma Antognoni', 47);
insert into users (username, password, name, salt) values ('thackett28', '0Mmgm5ogNE', 'Taber Hackett', 94);
insert into users (username, password, name, salt) values ('jsoan29', 'SlwVeNYNd', 'Joellyn Soan', 63);
insert into users (username, password, name, salt) values ('elutty2a', 'uqsD5Z2jK1Y', 'Elvera Lutty', 90);
insert into users (username, password, name, salt) values ('wold2b', 'QiRVtyV6l2', 'Washington Old', 63);
insert into users (username, password, name, salt) values ('bstreetfield2c', 'a7ugGdcnTH', 'Bartholemy Streetfield', 10);
insert into users (username, password, name, salt) values ('ggarbar2d', '8hzOuVvKRTU', 'Grantham Garbar', 52);
insert into users (username, password, name, salt) values ('bmoiser2e', 'J8bknE', 'Bartie Moiser', 81);
insert into users (username, password, name, salt) values ('wlindro2f', 'lzgcgQ8lZsN', 'Win Lindro', 87);
insert into users (username, password, name, salt) values ('ncunah2g', '3H07Su', 'Nikos Cunah', 57);
insert into users (username, password, name, salt) values ('ohardage2h', 'y23Kzp0h7uG', 'Ottilie Hardage', 18);
insert into users (username, password, name, salt) values ('bdensell2i', '5AJV0oGHgCF', 'Burnaby Densell', 68);
insert into users (username, password, name, salt) values ('dmeaden2j', 'v1xz7j', 'Danella Meaden', 62);
insert into users (username, password, name, salt) values ('kbernaert2k', 'H4uIFoSIE', 'Kristal Bernaert', 36);
insert into users (username, password, name, salt) values ('goneal2l', 'DkyOxS', 'Giffard O''Neal', 47);
insert into users (username, password, name, salt) values ('bgodfrey2m', 'W2lkfd8Oy9qr', 'Barnabe Godfrey', 2);
insert into users (username, password, name, salt) values ('sgilliat2n', 'eSSStChxjiOO', 'Suzann Gilliat', 12);
insert into users (username, password, name, salt) values ('kperigoe2o', 'I9bik5', 'Kit Perigoe', 41);
insert into users (username, password, name, salt) values ('mcharrett2p', 'tRgfT6Bcs', 'Maddy Charrett', 1);
insert into users (username, password, name, salt) values ('bphelipeaux2q', '4j7UXWhEMG', 'Baxie Phelipeaux', 29);
insert into users (username, password, name, salt) values ('jhinkes2r', 'jTYa12CiHUZ', 'Janenna Hinkes', 96);

insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Torry Lazonby', '#6ce6cd', 'Morbi vel lectus in quam fringilla rhoncus.', '#b7a93a', 'https://placebear.com/512/512', null, 'Duis mattis egestas metus. Aenean fermentum.', '#4878fa', 48);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Tessy Coole', '#af9ebd', 'Donec dapibus.', '#8b7cee', 'https://placebear.com/512/512', null, 'Pellentesque at nulla. Suspendisse potenti.', '#c4cb8f', 12);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Claudina Almey', '#b4dc7f', 'In hac habitasse platea dictumst.', '#98cb6e', 'https://placebear.com/512/512', null, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', '#ed58fc', 65);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Feliza Wattinham', '#15a468', 'Mauris lacinia sapien quis libero.', '#9c255b', 'https://placebear.com/512/512', null, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '#bfd673', 87);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Adiana Soff', '#3d6e4d', 'Pellentesque viverra pede ac diam.', '#ebc986', 'https://placebear.com/512/512', null, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '#0c699f', 14);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Dominick Knowling', '#426216', 'Duis aliquam convallis nunc.', '#3d9027', 'https://placebear.com/512/512', null, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '#047103', 68);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Noe Jiggens', '#9e50af', 'Sed ante.', '#5eec0d', 'https://placebear.com/512/512', null, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '#572d26', 24);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Dane Carlon', '#d484b4', 'Vestibulum sed magna at nunc commodo placerat.', '#f9308e', 'https://placebear.com/512/512', null, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '#7be680', 28);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Liv Whale', '#5f6e1e', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '#ddf92a', 'https://placebear.com/512/512', null, 'Integer tincidunt ante vel ipsum.', '#88b9ca', 82);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Magda Gosz', '#5ac3bd', 'Morbi a ipsum.', '#dc51b6', 'https://placebear.com/512/512', null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '#53c1b9', 46);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Gerhard Nannini', '#f7460b', 'Morbi non lectus.', '#62d493', 'https://placebear.com/512/512', null, 'Fusce consequat. Nulla nisl. Nunc nisl.', '#35a8eb', 18);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Melodie Vassbender', '#479506', 'Nullam molestie nibh in lectus.', '#588378', 'https://placebear.com/512/512', null, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '#79685c', 56);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Denni Dumphrey', '#5b49b1', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '#183267', 'https://placebear.com/512/512', null, 'Duis aliquam convallis nunc.', '#44ab38', 32);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Jermaine Vinten', '#340394', 'Maecenas tincidunt lacus at velit.', '#3dc98b', 'https://placebear.com/512/512', null, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '#10d487', 93);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Clemens Gooday', '#5e4ab0', 'Nulla nisl.', '#a812da', 'https://placebear.com/512/512', null, 'Aliquam erat volutpat. In congue.', '#f740ef', 45);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Emalee Calbrathe', '#f05f1b', 'Duis at velit eu est congue elementum.', '#b202c7', 'https://placebear.com/512/512', null, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '#9b0584', 17);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Perle Spira', '#44c33c', 'Nam nulla.', '#a14710', 'https://placebear.com/512/512', null, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '#b6bb65', 89);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Porty Buckner', '#cdda4b', 'Fusce consequat.', '#2036dd', 'https://placebear.com/512/512', null, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '#707240', 62);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Laurie Drissell', '#ce8a9b', 'Morbi quis tortor id nulla ultrices aliquet.', '#f23957', 'https://placebear.com/512/512', null, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '#c72f7d', 31);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Norina Wythill', '#6c1647', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '#431cab', 'https://placebear.com/512/512', null, 'Mauris sit amet eros.', '#c6b584', 74);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Vinni Brenton', '#20e82b', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '#088114', 'https://placebear.com/512/512', null, 'Mauris ullamcorper purus sit amet nulla.', '#8430ca', 48);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Gunther Kift', '#8abdcf', 'In eleifend quam a odio.', '#052279', 'https://placebear.com/512/512', null, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '#082be7', 9);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Iggy Richardeau', '#2f50e0', 'Phasellus id sapien in sapien iaculis congue.', '#1bc26e', 'https://placebear.com/512/512', null, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '#39a551', 28);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Domingo Aiston', '#63a2f0', 'In eleifend quam a odio.', '#ec7161', 'https://placebear.com/512/512', null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '#672359', 59);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Terrell Oboy', '#686110', 'Quisque id justo sit amet sapien dignissim vestibulum.', '#9f823c', 'https://placebear.com/512/512', null, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '#905c19', 97);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Hendrik Markl', '#4f9dab', 'Donec ut mauris eget massa tempor convallis.', '#17bc02', 'https://placebear.com/512/512', null, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '#a2c4cc', 24);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Danna Overstreet', '#ff1c35', 'In eleifend quam a odio.', '#69bfad', 'https://placebear.com/512/512', null, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '#0b33fb', 14);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Jo ann Pearmine', '#de329a', 'Duis bibendum.', '#e05432', 'https://placebear.com/512/512', null, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '#a7b22c', 61);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Husain Como', '#248081', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '#221023', 'https://placebear.com/512/512', null, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '#64b782', 37);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Lilah Highway', '#87fd50', 'Aenean fermentum.', '#2b3496', 'https://placebear.com/512/512', null, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '#037ccd', 26);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Alexina Tollow', '#e3f9ab', 'Sed sagittis.', '#fe3540', 'https://placebear.com/512/512', null, 'Duis aliquam convallis nunc.', '#048695', 25);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Jenn Dullingham', '#4af5f4', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '#0162f0', 'https://placebear.com/512/512', null, 'Duis at velit eu est congue elementum.', '#939c41', 66);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Onfroi Atto', '#6e965a', 'Morbi non quam nec dui luctus rutrum.', '#238e97', 'https://placebear.com/512/512', null, 'Fusce consequat. Nulla nisl.', '#a44bd5', 78);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Elmira Goaks', '#bcfe58', 'Integer non velit.', '#e0b41b', 'https://placebear.com/512/512', null, 'Aliquam erat volutpat.', '#2bd1e2', 75);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Carmel Haggus', '#589352', 'In quis justo.', '#a6a608', 'https://placebear.com/512/512', null, 'Suspendisse ornare consequat lectus.', '#f35c11', 41);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Tristam Leap', '#3e3153', 'Maecenas tincidunt lacus at velit.', '#b6e7d2', 'https://placebear.com/512/512', null, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '#745a97', 74);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Mellisent Hardson', '#2bf16e', 'Morbi non quam nec dui luctus rutrum.', '#43b28c', 'https://placebear.com/512/512', null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '#d08a41', 98);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Antin Callaghan', '#29a655', 'Duis ac nibh.', '#81b98e', 'https://placebear.com/512/512', null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '#f2d69d', 24);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Dayle Lerhinan', '#fe48ba', 'Nam nulla.', '#7afd6b', 'https://placebear.com/512/512', null, 'Fusce consequat.', '#9288f2', 92);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Kellen Gilffilland', '#21583f', 'Aliquam quis turpis eget elit sodales scelerisque.', '#f97e5d', 'https://placebear.com/512/512', null, 'Aliquam erat volutpat. In congue.', '#d352fd', 90);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Bryce Toll', '#d20deb', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '#2908b0', 'https://placebear.com/512/512', null, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '#2fd80c', 44);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Miguelita Lusk', '#f49678', 'In hac habitasse platea dictumst.', '#03a99e', 'https://placebear.com/512/512', null, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', '#3391b0', 51);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Pauly Willmot', '#091ae6', 'Nullam varius.', '#39ebd3', 'https://placebear.com/512/512', null, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '#33c24b', 12);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Zollie Squelch', '#9e007a', 'Suspendisse potenti.', '#2cc44d', 'https://placebear.com/512/512', null, 'Nulla ac enim.', '#ae2d12', 86);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Gherardo Stroton', '#f5812c', 'Duis at velit eu est congue elementum.', '#86eea3', 'https://placebear.com/512/512', null, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '#e76630', 33);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Moises Dimitrijevic', '#fec3d4', 'Nunc rhoncus dui vel sem.', '#9ccbc8', 'https://placebear.com/512/512', null, 'Curabitur gravida nisi at nibh.', '#034090', 73);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Katherine Antoniewicz', '#5e19c2', 'Quisque ut erat.', '#8938e6', 'https://placebear.com/512/512', null, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '#fd7cf3', 10);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Barry Saylor', '#2e341c', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '#b6c586', 'https://placebear.com/512/512', null, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '#5f8e88', 82);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Milty Crosse', '#510ac6', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '#1b33df', 'https://placebear.com/512/512', null, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '#48d7df', 23);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Martino Lanfere', '#ad5ec6', 'Vestibulum rutrum rutrum neque.', '#8f2d5a', 'https://placebear.com/512/512', null, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '#6add64', 35);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Constantine Powdrell', '#0baf86', 'Nulla mollis molestie lorem.', '#94ffdf', 'https://placebear.com/512/512', null, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '#f3ac84', 13);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Wynn Ackred', '#77e696', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '#77c794', 'https://placebear.com/512/512', null, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '#8857c4', 23);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Sarita Biles', '#248153', 'Proin eu mi.', '#9e6bd3', 'https://placebear.com/512/512', null, 'Nunc nisl.', '#5ff066', 99);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Farrand Dugood', '#3ea0a4', 'Pellentesque ultrices mattis odio.', '#75045f', 'https://placebear.com/512/512', null, 'Quisque ut erat.', '#f5bf60', 100);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Haleigh Proppers', '#8c856c', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '#ec4728', 'https://placebear.com/512/512', null, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '#6a1752', 93);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Tamqrah Ferrero', '#cc8602', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '#b9f09b', 'https://placebear.com/512/512', null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '#07b4a8', 38);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Lucius Covotti', '#176f6a', 'In sagittis dui vel nisl.', '#6541ad', 'https://placebear.com/512/512', null, 'Aenean fermentum.', '#a8e5b3', 17);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Florance Tumulty', '#9a868a', 'Mauris sit amet eros.', '#1b4249', 'https://placebear.com/512/512', null, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '#a56a5c', 23);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Sabrina Cleever', '#4eb3b5', 'Etiam vel augue.', '#12d1d2', 'https://placebear.com/512/512', null, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '#ee4c82', 94);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Orin Kirley', '#f0badd', 'Donec quis orci eget orci vehicula condimentum.', '#839e2c', 'https://placebear.com/512/512', null, 'Ut tellus.', '#3d3739', 46);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Kennith Cordes', '#cde24d', 'Nullam molestie nibh in lectus.', '#006e42', 'https://placebear.com/512/512', null, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '#6becde', 50);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Pete Gaitone', '#9f3741', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '#ea9792', 'https://placebear.com/512/512', null, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '#f1fd08', 12);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Ariel Brock', '#d43a48', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '#308409', 'https://placebear.com/512/512', null, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '#d25b33', 92);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Britte Lukock', '#9955f1', 'Ut tellus.', '#082e59', 'https://placebear.com/512/512', null, 'Donec dapibus. Duis at velit eu est congue elementum.', '#83e394', 38);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Germana Bartlet', '#4ac50d', 'Curabitur at ipsum ac tellus semper interdum.', '#095615', 'https://placebear.com/512/512', null, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '#383a18', 63);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Stephie Westwood', '#546e05', 'Sed ante.', '#34d509', 'https://placebear.com/512/512', null, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '#96d4a8', 87);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Bruis Kiely', '#e6a675', 'Suspendisse potenti.', '#0f0efb', 'https://placebear.com/512/512', null, 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '#a10418', 99);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Saxon Barday', '#3f2edb', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '#fd2daa', 'https://placebear.com/512/512', null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '#120a15', 14);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Chrysa Andrault', '#5b855e', 'Fusce posuere felis sed lacus.', '#b42baf', 'https://placebear.com/512/512', null, 'Duis bibendum.', '#32bdff', 69);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Cherie Shadrack', '#e808a1', 'Integer ac neque.', '#a8a9b5', 'https://placebear.com/512/512', null, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '#6eb287', 34);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Alfi Lesser', '#83b283', 'Vivamus in felis eu sapien cursus vestibulum.', '#3f701b', 'https://placebear.com/512/512', null, 'Duis consequat dui nec nisi volutpat eleifend.', '#32500c', 91);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Patrick Tommis', '#2c47e4', 'Suspendisse accumsan tortor quis turpis.', '#f3f417', 'https://placebear.com/512/512', null, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '#526e06', 20);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Jakob Collinwood', '#8ca421', 'Morbi a ipsum.', '#9adecb', 'https://placebear.com/512/512', null, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '#f42895', 95);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Skyler Drance', '#1f4d3e', 'Duis at velit eu est congue elementum.', '#eeab8f', 'https://placebear.com/512/512', null, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '#e9c820', 59);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Theobald Ormiston', '#86e16d', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '#b09340', 'https://placebear.com/512/512', null, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', '#a2127d', 36);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Caz Struthers', '#ed27a1', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '#54eb80', 'https://placebear.com/512/512', null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '#08dafe', 26);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Ara Senechault', '#33d6cd', 'Donec ut mauris eget massa tempor convallis.', '#618753', 'https://placebear.com/512/512', null, 'Nullam molestie nibh in lectus. Pellentesque at nulla.', '#126f65', 85);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Elka Meldrum', '#fc2cb4', 'Quisque ut erat.', '#154a1d', 'https://placebear.com/512/512', null, 'Quisque ut erat.', '#549680', 54);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Vanessa Caulket', '#b39bd3', 'Integer a nibh.', '#65efad', 'https://placebear.com/512/512', null, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '#30abbc', 77);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Marie-jeanne Bernasek', '#b710fa', 'Morbi a ipsum.', '#d5cd76', 'https://placebear.com/512/512', null, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '#ebdd9a', 19);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Elsy Harmar', '#11fb53', 'Pellentesque ultrices mattis odio.', '#6fbb18', 'https://placebear.com/512/512', null, 'Integer tincidunt ante vel ipsum.', '#a3aa66', 11);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Fitz Sickling', '#7ea849', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '#bc3162', 'https://placebear.com/512/512', null, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '#5c3e63', 12);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Foss MacDavitt', '#0ea91f', 'Suspendisse ornare consequat lectus.', '#90f907', 'https://placebear.com/512/512', null, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '#185719', 20);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Emilee Lesaunier', '#b8557c', 'Curabitur at ipsum ac tellus semper interdum.', '#161b9c', 'https://placebear.com/512/512', null, 'Integer ac leo. Pellentesque ultrices mattis odio.', '#dd229a', 49);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Jamey Gini', '#88ce61', 'Nam tristique tortor eu pede.', '#eedc88', 'https://placebear.com/512/512', null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '#c1d668', 83);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Tim Kofax', '#9535d2', 'Vivamus vestibulum sagittis sapien.', '#51d62b', 'https://placebear.com/512/512', null, 'Etiam vel augue.', '#cf9379', 53);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Delphine Clotworthy', '#b6df39', 'Donec dapibus.', '#d3ecb1', 'https://placebear.com/512/512', null, 'In blandit ultrices enim.', '#4db5cd', 42);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Letizia Burnes', '#c7a7ca', 'Vivamus vestibulum sagittis sapien.', '#e0c067', 'https://placebear.com/512/512', null, 'Pellentesque ultrices mattis odio.', '#f7a663', 97);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Arvy Shirer', '#a5f6f5', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '#a0405b', 'https://placebear.com/512/512', null, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '#04ce2a', 15);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Nelie Clooney', '#e01f73', 'In hac habitasse platea dictumst.', '#a87cbf', 'https://placebear.com/512/512', null, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '#3154a0', 2);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Clovis Bontein', '#3443b7', 'Etiam pretium iaculis justo.', '#fdd387', 'https://placebear.com/512/512', null, 'Nulla nisl. Nunc nisl.', '#69bb48', 98);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Isiahi Jakubovics', '#cfcb42', 'Duis aliquam convallis nunc.', '#a1750c', 'https://placebear.com/512/512', null, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '#03141c', 37);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Michaeline Sorbey', '#4f25e0', 'Aliquam non mauris.', '#9754fa', 'https://placebear.com/512/512', null, 'Nam tristique tortor eu pede.', '#2eb740', 44);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Lindi Rosenblath', '#30eb2b', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '#fa3c03', 'https://placebear.com/512/512', null, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '#5c6a4f', 100);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Eleonora Ferroli', '#6ed08b', 'Integer ac neque.', '#0437b3', 'https://placebear.com/512/512', null, 'Nulla ut erat id mauris vulputate elementum.', '#092dfb', 31);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Karie Bladon', '#c0cfbd', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '#4f365c', 'https://placebear.com/512/512', null, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '#8d8505', 49);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Linn Lindemann', '#3b876c', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '#ecf731', 'https://placebear.com/512/512', null, 'Duis ac nibh.', '#7c8a33', 35);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Brittaney Labbet', '#ed0493', 'Nulla tempus.', '#46c2c2', 'https://placebear.com/512/512', null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '#eb798a', 44);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Sharia Bradder', '#824a14', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '#d6720f', 'https://placebear.com/512/512', null, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '#de4917', 27);
insert into billboards (name, background, message, message_color, url, data, information, information_color, owner) values ('Justinn Merrydew', '#7f4532', 'Suspendisse ornare consequat lectus.', '#3d34ce', 'https://placebear.com/512/512', null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '#7a7977', 33);

insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('12:03', '4:10', 781, 28, 98, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('17:02', '12:33', 1282, 781, 57, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('19:59', '15:40', 1346, 755, 15, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('20:09', '6:14', 1069, 572, 84, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('13:17', '14:18', 895, 437, 19, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('10:39', '14:29', 707, 864, 91, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('21:42', '23:27', 874, 882, 38, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:48', '17:38', 472, 799, 88, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:07', '5:38', 621, 419, 98, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('16:56', '15:16', 673, 913, 54, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('9:20', '9:50', 1270, 1099, 41, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:47', '13:31', 712, 1215, 39, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('21:45', '14:53', 1122, 845, 75, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('4:10', '2:42', 528, 388, 43, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:04', '19:16', 106, 1231, 56, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('6:49', '10:42', 1105, 529, 95, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:54', '18:15', 1232, 1106, 11, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('19:59', '6:24', 37, 709, 86, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:03', '8:51', 211, 760, 65, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('14:47', '5:12', 1316, 166, 11, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('17:01', '3:00', 996, 218, 83, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:58', '1:55', 259, 234, 14, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('20:28', '17:45', 1425, 915, 10, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('12:23', '20:41', 407, 614, 8, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:06', '1:45', 456, 1298, 6, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('4:24', '21:18', 703, 1238, 59, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('7:43', '16:18', 1014, 580, 96, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('5:39', '22:58', 893, 231, 19, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:53', '17:46', 160, 70, 75, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:10', '9:53', 767, 870, 1, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('19:14', '7:55', 110, 141, 82, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:50', '22:58', 366, 1201, 75, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('17:34', '17:19', 524, 286, 58, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('1:03', '21:10', 693, 865, 36, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:32', '13:58', 1114, 208, 16, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('1:32', '11:05', 1409, 369, 25, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('4:17', '9:52', 1264, 1109, 14, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('3:02', '23:13', 1148, 950, 72, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('7:50', '19:32', 124, 1179, 34, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('5:08', '11:45', 985, 1084, 58, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('16:21', '11:02', 581, 741, 25, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:54', '2:36', 374, 212, 45, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('19:02', '1:36', 109, 336, 54, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:39', '13:28', 1190, 112, 86, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:57', '21:26', 1079, 990, 21, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('14:22', '21:38', 1226, 1256, 31, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('6:31', '17:29', 120, 1252, 37, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('14:35', '11:25', 1422, 207, 32, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('20:57', '2:32', 81, 783, 82, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:26', '9:32', 753, 417, 4, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('13:47', '0:08', 1319, 825, 99, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:32', '3:49', 46, 910, 26, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('10:26', '16:27', 652, 991, 39, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:14', '19:22', 865, 1089, 18, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('3:56', '9:20', 1340, 1266, 18, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:09', '5:44', 430, 359, 86, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:54', '1:45', 252, 1111, 83, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:26', '6:24', 1368, 1007, 77, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:25', '8:51', 958, 276, 88, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('21:20', '16:24', 838, 999, 25, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('10:00', '20:15', 115, 825, 92, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('11:03', '1:01', 110, 645, 48, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('13:22', '21:09', 396, 422, 75, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:43', '18:59', 838, 479, 59, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('6:50', '14:31', 1096, 1356, 11, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('19:26', '15:14', 411, 427, 30, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:42', '20:44', 378, 419, 56, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('4:45', '15:03', 1162, 1393, 58, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:13', '15:10', 412, 481, 76, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:26', '3:55', 1279, 38, 26, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:47', '23:57', 1189, 1195, 74, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:56', '4:26', 1015, 286, 6, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:13', '5:40', 433, 258, 55, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('7:30', '2:35', 1061, 579, 76, 5);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('20:48', '17:17', 384, 1055, 3, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:23', '1:13', 102, 3, 95, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('10:26', '18:21', 936, 932, 47, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:47', '10:35', 519, 843, 5, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('11:38', '19:35', 645, 560, 89, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('13:47', '20:56', 1381, 911, 32, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('15:07', '18:00', 633, 1057, 35, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:59', '1:02', 1321, 155, 33, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('18:56', '8:01', 1024, 327, 5, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('10:13', '14:10', 971, 803, 8, 7);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('11:01', '13:20', 285, 457, 83, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('22:29', '9:44', 12, 522, 78, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('23:51', '12:29', 800, 456, 21, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('14:26', '14:01', 1005, 580, 93, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('13:22', '12:01', 253, 481, 30, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('11:42', '16:10', 338, 1036, 85, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('20:28', '8:05', 1290, 185, 94, 2);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('2:21', '16:16', 62, 1207, 93, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('1:42', '22:51', 707, 379, 27, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('3:49', '22:07', 1372, 1032, 5, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('7:11', '8:01', 471, 616, 33, 1);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('9:45', '20:40', 105, 483, 66, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('1:42', '14:00', 636, 1297, 19, 6);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('17:58', '12:33', 795, 1066, 62, 3);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('14:11', '18:48', 93, 435, 66, 4);
insert into schedule (start_time, end_time, duration, recurs, billboard, weekday) values ('0:11', '20:08', 729, 958, 77, 6);

insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, false, 69);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 9);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, false, 100);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, true, 67);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 14);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, true, 14);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 73);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 42);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, true, 83);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 47);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, false, 41);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 99);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 98);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 48);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 76);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 74);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 11);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 37);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, true, 77);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 54);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 99);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, true, 96);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 76);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, false, 52);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 85);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 63);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 57);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 32);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 82);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 14);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 29);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, true, 62);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 85);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 44);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 1);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, true, 41);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 36);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 62);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 34);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 76);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 14);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, false, 25);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 26);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 4);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 78);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, true, 42);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 93);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, true, 87);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, true, 17);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 79);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 61);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 69);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 47);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, false, 60);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, true, 48);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, true, 11);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 53);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 19);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 27);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 27);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 90);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 36);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 93);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 84);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 30);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, true, 83);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 42);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, false, 58);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 54);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 55);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 20);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 60);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 45);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, true, 91);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 59);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, true, 26);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 41);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, false, false, 22);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, false, 43);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, false, false, 59);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, false, 11);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 4);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, false, 68);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 25);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, false, true, 19);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, false, 5);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, false, false, 45);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, false, 43);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 99);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 25);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 57);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, false, 93);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 78);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 23);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, true, 75);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, false, 76);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, false, true, false, 29);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, true, true, false, 55);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (false, true, true, true, 60);
insert into permissions (create_billboards, edit_billboards, schedule_billboards, edit_users, user) values (true, false, true, true, 40);
